# Do `sudo killall -9 bluetoothd` on your host before starting.

name: linakcontroller
services:
  linakcontroller:
    build:
      context: ../..
      dockerfile: recipes/docker/Dockerfile
    restart: always

    tmpfs:
      - "/run"

    env_file:
      - .env

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

      # remember paired bluetooth devices:
      - "./data/bluetooth/:/var/lib/bluetooth/:rw"

    # required for bluetooth:
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
