# Do `sudo killall -9 bluetoothd` on your host before starting.

name: linakcontroller
version: '3'
services:
  linakcontroller:
    build:
      context: ../..
      dockerfile: recipes/docker/Dockerfile
    restart: always

    environment:
      LC_MAC_ADDRESS: "ab:ab:ab:ab:ab:ab"

    volumes:
      # remember paired bluetooth devices:
      - "./data/bluetooth/:/var/lib/bluetooth/:rw"

    # required for bluetooth:
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
